name: 📚 Documentation Changes
description: Use this template to register an issue for documentation changes
labels: [documentation, backend]
projects: alechkos/8
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > **ONCE YOU ASSIGNED YOURSELF TO THE ISSUE, THAT ISSUE WILL BE MOVED FROM `To Do` TO `In Progress` AND VICE VERSA**

        <details>
          <summary>
          
          ### How can I assign myself to the issue?
          
          </summary>

          #### The button is on the top right:
          ![](https://github.com/alechkos/vzou-frontend/assets/93551621/d5d54ea9-aded-43ee-9f86-807c9b5ed55c)

        </details>
  - type: textarea
    attributes:
      label: Description
      description: |
        **CLEARY DESCRIBE DOCUMENTATION CHANGES YOU ARE GOING TO PROVIDE,
        YOU CAN ADD PICTURES IF YOU WANT TO:**
    validations:
      required: true