name: Automerge

on:
  push:
    branches:
      - master

jobs:
  automerge:
    name: Automerge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Merge 'develop' to 'release'
        uses: richard-scott/automerger-action@v1.0.4
        with:
          github_token: ${{ secrets.PAC_TOKEN }}
          source: 'develop'
          target: 'release'
          message: '${{ github.event.commits[0].message }}'
